[testenv:bootstrap]
deps =
    jinja2
    tox
skip_install = true
commands =
    python ci/bootstrap.py --no-env
    pytest --cov=placades --cov-report=term-missing
passenv =
    *

[tox]
envlist =
    clean,
    check,
    docs,
    {py311,py312,py313,py314},
    report
ignore_basepython_conflict = true

[testenv]
extras = test
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
    PYTHONIOENCODING = utf-8
    PYTHONUTF8 = 1
    COVERAGE_FILE={toxinidir}/.coverage.{envname}
passenv =
    *
usedevelop = true
deps =
    pytest
    coverage
commands =
    coverage run --rcfile={toxinidir}/.coveragerc -m pytest -vv {posargs}

[testenv:report]
deps =
    coverage
skip_install = true
setenv =
    COVERAGE_FILE={toxinidir}/.coverage
commands =
    coverage combine {toxinidir}
    coverage report
    coverage html

[testenv:clean]
commands = coverage erase
skip_install = true
deps = coverage
setenv =
    COVERAGE_FILE={toxinidir}/.coverage

[testenv:check]
deps =
    build
    docutils
    check-manifest
    pre-commit
    readme-renderer
    pygments
    isort
    twine
skip_install = true
commands =
    python -m build .
    twine check dist/oemof*
    check-manifest {toxinidir}
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
usedevelop = true
deps =
    -r{toxinidir}/docs/requirements.txt
commands =
    sphinx-build {posargs:-E} -b html docs dist/docs
    sphinx-build -b linkcheck docs dist/docs
