name: build
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'

            python: '3.13'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'

            python: '3.13'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py311 (ubuntu)'

            python: '3.11'
            python_arch: 'x64'
            tox_env: 'py311'
            os: 'ubuntu-latest'
          - name: 'py312 (ubuntu)'

            python: '3.12'
            python_arch: 'x64'
            tox_env: 'py312'
            os: 'ubuntu-latest'
          - name: 'py313 (ubuntu)'

            python: '3.13'
            python_arch: 'x64'
            tox_env: 'py313'
            os: 'ubuntu-latest'
          - name: 'py313 (windows)'

            python: '3.13'
            python_arch: 'x64'
            tox_env: 'py313'
            os: 'windows-latest'
          - name: 'py313 (macos)'

            python: '3.13'
            python_arch: 'arm64'
            tox_env: 'py313'
            os: 'macos-latest'
    steps:
      - uses: actions/checkout@v4

        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5

        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.python_arch }}
      - name: install dependencies

        run: |
          python -m pip install --progress-bar=off -r ci/requirements.txt
          virtualenv --version
          pip --version
          tox --version
          pip list --format=freeze
      - name: test

        run: tox -e ${{ matrix.tox_env }} -v

  coverage-test:
    name: Run coverage test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout

        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python 3.11

        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies

        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Test with coverage

        run: |
          coverage run --rcfile=.coveragerc -m pytest -vv --junitxml=junit.xml
          coverage report --show-missing
          coverage xml

      - name: Upload coverage to Codecov

        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml

      - name: Upload test results to Codecov

        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
